# Generated by Django 4.1.4 on 2023-05-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('country', models.CharField(blank=True, choices=[('India', 'India'), ('Nepal', 'Nepal'), ('Indo-Nepal', 'Indo-Nepal')], max_length=200, null=True)),
                ('departure', models.TextField(blank=True, null=True)),
                ('speciality', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('map_link', models.TextField(blank=True, null=True)),
                ('days', models.IntegerField(default=0)),
                ('nights', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
