# Generated by Django 4.1.4 on 2023-05-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('facebook', models.TextField(default=None, null=True)),
                ('instagram', models.TextField(default=None, null=True)),
                ('twitter', models.TextField(default=None, null=True)),
                ('mail', models.TextField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('address', models.TextField(blank=True, null=True)),
                ('room', models.IntegerField(default=0)),
                ('hall', models.IntegerField(default=0)),
                ('kitchen', models.IntegerField(default=0)),
                ('bathroom', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('sale', models.BooleanField(default=False)),
                ('rent', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('parking', models.BooleanField(default=False)),
                ('camera', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('power', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('garbage_disposal', models.BooleanField(default=False)),
                ('modular_kitchen', models.BooleanField(default=False)),
                ('hot_water', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('map_link', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.city')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('profession', models.TextField(default=None, null=True)),
                ('comment', models.TextField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.propertytype'),
        ),
    ]
