# Generated by Django 4.1.4 on 2023-05-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_agent_city_contact_gallery_property_propertytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app01.property'),
        ),
    ]
