# Generated by Django 4.1.4 on 2023-05-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_property_price_in_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.city'),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='facebook',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='instagram',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mail',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='twitter',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
