# Generated by Django 4.1.4 on 2023-05-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_agent_city_agent_phone_alter_agent_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='mail',
            new_name='email',
        ),
        migrations.AddField(
            model_name='agent',
            name='skype',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='tiktok',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
