# Generated by Django 4.1.4 on 2023-05-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_rename_mail_agent_email_agent_skype_agent_tiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='solar',
            field=models.BooleanField(default=False),
        ),
    ]
